In [1]:
from google.colab import drive
drive.mount('/content/drive/') # montar google drive como filesystem

Mounted at /content/drive/


In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [6]:
data=pd.read_csv("/content/drive/MyDrive/NLP Specialization/MODELO/Historia.csv")# cargar un csv a dataframe de pandas

In [7]:
data.head()

Unnamed: 0  ... CLASE
0           0  ...     1
1           1  ...     1
2           2  ...     1
3           3  ...     1
4           4  ...     1

[5 rows x 12 columns]

In [8]:
textos = data.iloc[:,1:]
textos

TextoCrudo  ... CLASE
0     Alexander III of Macedon (Greek: Αλέξανδρος Γʹ...  ...     1
1     During his youth, Alexander was tutored by Ari...  ...     1
2     Alexander endeavoured to reach the "ends of th...  ...     1
3     Alexander's legacy includes the cultural diffu...  ...     1
4     Alexander was born in Pella, the capital of th...  ...     1
...                                                 ...  ...   ...
5937  There are nevertheless a number of contemporar...  ...     5
5938  Evidence suggests big-game hunter-gatherers cr...  ...     5
5939  Hunter-gatherers would eventually flourish all...  ...     5
5940  The Archaic period in the Americas saw a chang...  ...     5
5941   Media related to Hunter-gatherers at Wikimedi...  ...     5

[5942 rows x 11 columns]

In [9]:
X = textos.iloc[:,3:8].values

In [10]:
type(X)

numpy.ndarray

In [11]:
X

array([[5765., 4813., 4377., 2796., 3298.],
       [5726., 5416., 4039., 3072., 2520.],
       [3986., 3825., 3753., 4337., 2094.],
       ...,
       [2534., 2625., 2667., 2598., 5156.],
       [2173., 2227., 2068., 1861., 4283.],
       [ 106.,  103.,   73.,   75.,  253.]])

In [13]:
Y = textos.iloc[:,10].values 

In [14]:
type(Y)

numpy.ndarray

In [15]:
Y

array([1, 1, 1, ..., 5, 5, 5])

In [16]:
xtr,xtst,ytr,ytst=train_test_split(X,Y,test_size=.2,random_state=564)

In [17]:
xtrn = xtr / 10000

In [18]:
xtstn = xtst / 10000

In [19]:
len(xtr)

4753

In [20]:
len(ytr)

4753

In [21]:
len(xtst)

1189

In [22]:
len(ytst)

1189

In [23]:
xtstn.shape[1:]

(5,)

In [24]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [25]:
modelo = Sequential()

In [26]:
modelo.add(Dense(128,input_shape = xtstn.shape[1:]))

In [27]:
modelo.add(Dense(6,activation="softmax"))

In [28]:
modelo.compile(optimizer = "adam", loss = "sparse_categorical_crossentropy", metrics =["acc"] )

In [29]:
modelo.fit(xtrn,ytr,epochs=120,batch_size=105,validation_split=.1)

Epoch 1/120
41/41 [==============================] - 1s 12ms/step - loss: 1.7088 - acc: 0.3001 - val_loss: 1.5268 - val_acc: 0.5546
Epoch 2/120
41/41 [==============================] - 0s 3ms/step - loss: 1.4800 - acc: 0.6602 - val_loss: 1.3682 - val_acc: 0.6324
Epoch 3/120
41/41 [==============================] - 0s 2ms/step - loss: 1.3310 - acc: 0.7010 - val_loss: 1.2339 - val_acc: 0.7647
Epoch 4/120
41/41 [==============================] - 0s 2ms/step - loss: 1.1981 - acc: 0.7794 - val_loss: 1.1195 - val_acc: 0.7773
Epoch 5/120
41/41 [==============================] - 0s 2ms/step - loss: 1.0838 - acc: 0.7894 - val_loss: 1.0234 - val_acc: 0.7941
Epoch 6/120
41/41 [==============================] - 0s 2ms/step - loss: 0.9922 - acc: 0.7938 - val_loss: 0.9459 - val_acc: 0.8256
Epoch 7/120
41/41 [==============================] - 0s 2ms/step - loss: 0.9168 - acc: 0.8057 - val_loss: 0.8793 - val_acc: 0.8109
Epoch 8/120
41/41 [==============================] - 0s 2ms/step - loss: 0.8479 - 

In [32]:
modelo.evaluate(xtstn,ytst)

38/38 [==============================] - 0s 1ms/step - loss: 0.4745 - acc: 0.8495


[0.47448304295539856, 0.849453330039978]

In [31]:
xtst

array([[ 881.,  876., 1015.,  855., 4319.],
       [ 110.,  151.,  137.,  107.,   65.],
       [ 985., 1090., 1014., 1309.,  735.],
       ...,
       [3364., 3117., 3077., 2500., 6625.],
       [ 564.,  684.,  517.,  304.,  959.],
       [1101., 1163., 1471.,  998., 1053.]])

In [ ]:
xtst[0],ytst[0]

(array([ 823.,  769.,  949.,  793., 4165.]), 5)

In [ ]:
modelo.predict(xtst[0].reshape(1, -1)),ytst[0]

(array([[0., 0., 0., 0., 0., 1.]], dtype=float32), 5)

In [ ]:
np.argmax(modelo.predict(xtst[0].reshape(1, -1))) == ytst[0]

True

In [ ]:
len(xtst)

1189

In [ ]:
aciertos = 0
for i in range(len(xtst)):
     if np.argmax(modelo.predict(xtst[i].reshape(1, -1))) == ytst[i]:
       aciertos +=1
print("aciertos: ",aciertos)       

aciertos:  1019


In [ ]:
print("Accuracy: ", aciertos / len(xtst))

Accuracy:  0.8570227081581161


In [35]:
modelo.save_weights("/content/drive/MyDrive/NLP Specialization/MODELO/Historia.h5")

In [34]:
pifiadas = 0
indicePifiadas = []
for i in range(len(xtst)):
     if np.argmax(modelo.predict(xtst[i].reshape(1, -1))) != ytst[i]:
       pifiadas +=1
       indicePifiadas.append(i)
print("pifiadas: ",pifiadas) 
print(len(indicePifiadas))

pifiadas:  178
178


In [ ]:
print("pifiadas: ",pifiadas) 

pifiadas:  170


In [36]:
Xn = X / 10000

In [37]:
Xn 

array([[0.5765, 0.4813, 0.4377, 0.2796, 0.3298],
       [0.5726, 0.5416, 0.4039, 0.3072, 0.252 ],
       [0.3986, 0.3825, 0.3753, 0.4337, 0.2094],
       ...,
       [0.2534, 0.2625, 0.2667, 0.2598, 0.5156],
       [0.2173, 0.2227, 0.2068, 0.1861, 0.4283],
       [0.0106, 0.0103, 0.0073, 0.0075, 0.0253]])

In [38]:
pifiadas = 0
indicePifiadas = []
for i in range(len(Xn)):
     if np.argmax(modelo.predict(Xn[i].reshape(1, -1))) != Y[i]:
       pifiadas += 1
       indicePifiadas.append(i)
print("pifiadas: ",pifiadas) 
print(len(indicePifiadas))

pifiadas:  857
857


In [39]:
textos

TextoCrudo  ... CLASE
0     Alexander III of Macedon (Greek: Αλέξανδρος Γʹ...  ...     1
1     During his youth, Alexander was tutored by Ari...  ...     1
2     Alexander endeavoured to reach the "ends of th...  ...     1
3     Alexander's legacy includes the cultural diffu...  ...     1
4     Alexander was born in Pella, the capital of th...  ...     1
...                                                 ...  ...   ...
5937  There are nevertheless a number of contemporar...  ...     5
5938  Evidence suggests big-game hunter-gatherers cr...  ...     5
5939  Hunter-gatherers would eventually flourish all...  ...     5
5940  The Archaic period in the Americas saw a chang...  ...     5
5941   Media related to Hunter-gatherers at Wikimedi...  ...     5

[5942 rows x 11 columns]

In [40]:
for i in textos.index:
  textos["Predicción"][i] =  np.argmax(modelo.predict(Xn[i].reshape(1, -1)))
textos  

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


TextoCrudo  ... CLASE
0     Alexander III of Macedon (Greek: Αλέξανδρος Γʹ...  ...     1
1     During his youth, Alexander was tutored by Ari...  ...     1
2     Alexander endeavoured to reach the "ends of th...  ...     1
3     Alexander's legacy includes the cultural diffu...  ...     1
4     Alexander was born in Pella, the capital of th...  ...     1
...                                                 ...  ...   ...
5937  There are nevertheless a number of contemporar...  ...     5
5938  Evidence suggests big-game hunter-gatherers cr...  ...     5
5939  Hunter-gatherers would eventually flourish all...  ...     5
5940  The Archaic period in the Americas saw a chang...  ...     5
5941   Media related to Hunter-gatherers at Wikimedi...  ...     5

[5942 rows x 11 columns]

In [41]:
textos.to_csv("/content/drive/MyDrive/NLP Specialization/MODELO/Historia.csv")