In [1]:
from google.colab import drive
drive.mount('/content/drive/') # montar google drive como filesystem

Mounted at /content/drive/


In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
data=pd.read_csv("/content/drive/MyDrive/DEEP LEARNING - ESPECIALIZACION  -COURSERA/NLP/Historia.csv")# cargar un csv a dataframe de pandas

In [4]:
data.head()

Unnamed: 0  ...  Clase5
0           0  ...   462.0
1           1  ...   522.0
2           2  ...  1348.0
3           3  ...  1088.0
4           4  ...   579.0

[5 rows x 8 columns]

In [5]:
textos = data.iloc[:,1:]
textos

Texto  Clase  ...  Clase4  Clase5
0      ['alexand', 'iii', 'macedon', 'greek', 'αλέξαν...      1  ...   317.0   462.0
1      ['bc', 'commonli', 'known', 'alexand', 'great'...      1  ...   279.0   522.0
2      ['pella', '356', 'bc', 'succeed', 'father', 'p...      1  ...   697.0  1348.0
3      ['age', 'thirti', 'creat', 'one', 'largest', '...      1  ...   829.0  1088.0
4      ['youth', 'alexand', 'tutor', 'aristotl', 'age...      1  ...   485.0   579.0
...                                                  ...    ...  ...     ...     ...
15005  ['south', 'chile', 'mont', 'verd', 'citat', 'n...      5  ...   618.0  1112.0
15006  ['common', 'style', 'stone', 'tool', 'product'...      5  ...   370.0  2110.0
15007  ['archaic', 'period', 'america', 'saw', 'chang...      5  ...   593.0  1405.0
15008  ['mobil', 'hunter-gather', 'individu', 'group'...      5  ...   572.0  1144.0
15009  ['poverti', 'point', 'dalton', 'plano', 'tradi...      5  ...   397.0   819.0

[15010 rows x 7 columns]

In [6]:
X = textos.iloc[:,2:].values

In [7]:
type(X)

numpy.ndarray

In [8]:
X

array([[1266.,  468.,  459.,  317.,  462.],
       [2073., 1007.,  740.,  279.,  522.],
       [1457., 1144., 1209.,  697., 1348.],
       ...,
       [ 682.,  782.,  739.,  593., 1405.],
       [ 641.,  560.,  526.,  572., 1144.],
       [ 485.,  474.,  472.,  397.,  819.]])

In [9]:
Y = textos.iloc[:,1].values 

In [10]:
type(Y)

numpy.ndarray

In [11]:
Y

array([1, 1, 1, ..., 5, 5, 5])

In [12]:
xtr,xtst,ytr,ytst=train_test_split(X,Y,test_size=.2,random_state=564)

In [13]:
xtrn = xtr / 1000

In [14]:
xtstn = xtst / 1000

In [15]:
len(xtr)

12008

In [16]:
len(ytr)

12008

In [17]:
len(xtst)

3002

In [18]:
len(ytst)

3002

In [19]:
xtstn.shape[1:]

(5,)

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [21]:
modelo = Sequential()

In [22]:
modelo.add(Dense(128,input_shape = xtstn.shape[1:]))

In [23]:
modelo.add(Dense(6,activation="softmax"))

In [24]:
modelo.compile(optimizer = "sgd", loss = "sparse_categorical_crossentropy", metrics =["acc"] )

In [25]:
modelo.fit(xtrn,ytr,epochs=240,batch_size=105,validation_split=.1)

Epoch 1/240
103/103 [==============================] - 1s 6ms/step - loss: 1.6534 - acc: 0.3029 - val_loss: 1.4602 - val_acc: 0.5945
Epoch 2/240
103/103 [==============================] - 0s 1ms/step - loss: 1.4120 - acc: 0.6279 - val_loss: 1.3161 - val_acc: 0.6744
Epoch 3/240
103/103 [==============================] - 0s 1ms/step - loss: 1.2796 - acc: 0.6979 - val_loss: 1.2152 - val_acc: 0.7077
Epoch 4/240
103/103 [==============================] - 0s 1ms/step - loss: 1.1793 - acc: 0.7348 - val_loss: 1.1381 - val_acc: 0.7236
Epoch 5/240
103/103 [==============================] - 0s 2ms/step - loss: 1.1001 - acc: 0.7418 - val_loss: 1.0783 - val_acc: 0.7294
Epoch 6/240
103/103 [==============================] - 0s 1ms/step - loss: 1.0460 - acc: 0.7485 - val_loss: 1.0280 - val_acc: 0.7352
Epoch 7/240
103/103 [==============================] - 0s 1ms/step - loss: 0.9973 - acc: 0.7540 - val_loss: 0.9861 - val_acc: 0.7402
Epoch 8/240
103/103 [==============================] - 0s 1ms/step - 

In [26]:
modelo.evaluate(xtstn,ytst)

94/94 [==============================] - 0s 811us/step - loss: 0.6684 - acc: 0.7765


[0.6683911681175232, 0.776482343673706]

In [27]:
xtst

array([[ 512.,  579.,  514.,  458., 1435.],
       [  77.,  177.,  317.,  331.,  104.],
       [1231.,  589.,  502.,  335., 1591.],
       ...,
       [ 418.,  468.,  466.,  273.,  578.],
       [ 404.,  462.,  882.,  422.,  230.],
       [1047.,  434.,  485.,  388.,  557.]])

In [28]:
xtst[0],ytst[0]

(array([ 512.,  579.,  514.,  458., 1435.]), 5)

In [29]:
modelo.predict(xtst[0].reshape(1, -1)),ytst[0]

(array([[0., 0., 0., 0., 0., 1.]], dtype=float32), 5)

In [30]:
np.argmax(modelo.predict(xtst[0].reshape(1, -1))) == ytst[0]

True

In [31]:
len(xtst)

3002

In [32]:
aciertos = 0
for i in range(len(xtst)):
     if np.argmax(modelo.predict(xtst[i].reshape(1, -1))) == ytst[i]:
       aciertos +=1
print("aciertos: ",aciertos)       

aciertos:  2311


In [33]:
print("Accuracy: ", aciertos / len(xtst))

Accuracy:  0.7698201199200533


In [34]:
modelo.save_weights("/content/drive/MyDrive/DEEP LEARNING - ESPECIALIZACION  -COURSERA/NLP/Historia.h5")

In [ ]:
modelo.save("/content/drive/MyDrive/DEEP LEARNING - ESPECIALIZACION  -COURSERA/NLP/MHistoriaFreq.h5")