In [4]:
import pandas as pd
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import keras as K
import pickle

In [6]:
from google.colab import drive
drive.mount('/content/drive/') # montar google drive com

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [7]:
textos = pd.read_csv("/content/drive/MyDrive/DEEP LEARNING - ESPECIALIZACION  -COURSERA/NLP/Historia.csv")

In [8]:
textos.head()

Unnamed: 0  ...  Clase5
0           0  ...   462.0
1           1  ...   522.0
2           2  ...  1348.0
3           3  ...  1088.0
4           4  ...   579.0

[5 rows x 8 columns]

In [9]:
textos = textos.iloc[:,1:]
textos

Texto  Clase  ...  Clase4  Clase5
0      ['alexand', 'iii', 'macedon', 'greek', 'αλέξαν...      1  ...   317.0   462.0
1      ['bc', 'commonli', 'known', 'alexand', 'great'...      1  ...   279.0   522.0
2      ['pella', '356', 'bc', 'succeed', 'father', 'p...      1  ...   697.0  1348.0
3      ['age', 'thirti', 'creat', 'one', 'largest', '...      1  ...   829.0  1088.0
4      ['youth', 'alexand', 'tutor', 'aristotl', 'age...      1  ...   485.0   579.0
...                                                  ...    ...  ...     ...     ...
15005  ['south', 'chile', 'mont', 'verd', 'citat', 'n...      5  ...   618.0  1112.0
15006  ['common', 'style', 'stone', 'tool', 'product'...      5  ...   370.0  2110.0
15007  ['archaic', 'period', 'america', 'saw', 'chang...      5  ...   593.0  1405.0
15008  ['mobil', 'hunter-gather', 'individu', 'group'...      5  ...   572.0  1144.0
15009  ['poverti', 'point', 'dalton', 'plano', 'tradi...      5  ...   397.0   819.0

[15010 rows x 7 columns]

In [11]:
X = textos.iloc[:,2:].values

In [12]:
Y = textos.iloc[:,1].values

In [13]:
Xn = X / 1000

In [14]:
len(Xn)

15010

In [15]:
modelo = Sequential()
modelo.add(Dense(128,input_shape = Xn.shape[1:]))
modelo.add(Dense(6,activation="softmax"))
modelo.compile(optimizer = "sgd", loss = "sparse_categorical_crossentropy", metrics =["acc"] )


In [16]:
modelo.load_weights('/content/drive/MyDrive/DEEP LEARNING - ESPECIALIZACION  -COURSERA/NLP/Historia.h5')

In [12]:
np.argmax(modelo.predict(Xn[10122].reshape(1, -1))),Y[10122]

(4, 4)

In [17]:
# url = "https://www.history.com/topics/cold-war/cuban-missile-crisis"
# url = "https://courses.lumenlearning.com/suny-hccc-worldhistory/chapter/the-seven-kings/"
# url = "https://heritagecalling.com/2019/02/22/a-brief-introduction-to-prehistoric-caves/"
# url = "https://www.ancient.eu/Medieval_Castle/" FALLO
# url = "https://www.britannica.com/event/Battle-of-Tours-732"
# url = "https://www.historytoday.com/archive/1683-siege-vienna"
# url = "https://www.sciencedirect.com/topics/social-sciences/early-modern-times"
# url = "https://www.sparknotes.com/lit/3musk/section15/"  LA PEGO Y NO SE PORQUE
# url = "https://marcopologencana.wordpress.com/2019/06/17/the-crazy-years-between-the-wars/"
# url = "https://www.nationalgeographic.com/news/2006/9/lucy-facts-on-early-human-ancestor/"
# url = "https://www.researchgate.net/publication/236765312_Spartacus_Film_and_History_and_Troy_From_Homer's_'Iliad'_to_Hollywood_Epic_review"
# url = "https://www.thespanishblog.com/2011/06/history-of-spain-the-carthaginians/"
url = "https://www.history.com/news/prehistoric-ages-timeline"




In [18]:
import pickle
def save_obj(obj, name ):
       with open(name + '.pkl', 'wb') as f:
           pickle.dump(obj, f, pickle.HIGHEST_PROTOCOL)

def load_obj(name ):
       with open('/content/drive/MyDrive/DEEP LEARNING - ESPECIALIZACION  -COURSERA/NLP//' + name + '.pkl', 'rb') as f:

           return pickle.load(f)

In [19]:
Vocabulario = load_obj("Vocabulario")
frecuencias = load_obj("Frecuencias")
clases_df = load_obj("clases_df")

In [20]:
clases_df

{1, 2, 3, 4, 5}

In [21]:
from requests import get # la vamos a usar para solicitar la página mediante su URL 
from bs4 import BeautifulSoup # biblioteca para web scraping
import pandas as pdf
import string                              
from nltk.corpus import stopwords # para remover palabras que no agregan significado          
from nltk.stem import PorterStemmer # para llevar las palabras a su forma raíz        
from nltk.tokenize import TweetTokenizer # para transformar cada palabra en un token
from IPython.display import clear_output
from collections import defaultdict
import numpy as np
import nltk
nltk.download('stopwords')

def etiquetas(palabras,frecuencias,clases):
    import numpy as np
    x = np.zeros((1, 6))
    for palabra in palabras:
        for t in clases:
            x[0,t] += frecuencias.get((palabra, t),0)
    x[0,0]=1
    return x

stop        = stopwords.words('english')
tokenizer   = TweetTokenizer(preserve_case = False, strip_handles = True, reduce_len = True)
stemmer     = PorterStemmer()
textosTest  = pd.DataFrame(columns = ['Texto'])
pagina    = get(url)
html      = BeautifulSoup(pagina.text,"html.parser")
parrafos  = [ x.text.strip() for x in html.findAll("p") if x.text != "\n" ]
for p in parrafos:
    palabras = p.split()
    if 15 <= len(palabras):
       clear_output( wait = True )
       print("procesando {}".format(url))
       texto_tokens = tokenizer.tokenize(p)
       texto_clean  = [ word for word in texto_tokens if word not in stop and word not in string.punctuation ]
       texto_stem   = [ stemmer.stem(word) for word in texto_clean ]
       textosTest   = textosTest.append({'Texto' : texto_stem}, ignore_index = True)

vocabularioTest = set([x for m in textosTest.index for x in textosTest.loc[m].Texto ])                



for i in clases_df:
    textosTest[f"Clase{i}"] = textosTest.Texto.apply(lambda x : etiquetas(x,frecuencias,clases_df)[0,i])
print("dataset terminado")
print(textosTest.describe())

procesando https://www.history.com/news/prehistoric-ages-timeline
dataset terminado
            Clase1       Clase2       Clase3       Clase4       Clase5
count    18.000000    18.000000    18.000000    18.000000    18.000000
mean   1334.111111  1210.277778  1049.444444   756.388889  2814.777778
std     696.195281   582.814652   516.978919   375.713148  2110.776845
min      38.000000    32.000000    41.000000    53.000000    47.000000
25%     923.750000   776.500000   708.500000   459.000000  1418.000000
50%    1562.500000  1403.500000  1233.500000   900.500000  2169.000000
75%    1897.000000  1611.750000  1417.500000  1027.500000  3885.250000
max    2210.000000  2217.000000  1717.000000  1220.000000  7426.000000


In [22]:
textosTest

Texto  Clase1  ...  Clase4  Clase5
0   [earth, ’, begin, trace, back, 4.5, billion, y...  1944.0  ...  1017.0  6510.0
1   [invent, tool, made, hunt, advanc, food, produ...  1512.0  ...  1031.0  3338.0
2   [divid, three, period, paleolith, old, stone, ...  2155.0  ...  1168.0  7426.0
3   [paleolith, period, roughli, 2.5, million, yea...  1990.0  ...  1127.0  5799.0
4   [ancient, human, paleolith, period, also, firs...  1828.0  ...   810.0  4119.0
5   [end, period, mark, end, last, ice, age, resul...  1004.0  ...   977.0  1773.0
6   [shell, mound, peopl, kitchen-midden, hunter-g...   652.0  ...   350.0  1364.0
7   [mesolith, period, 10,000, b, c, 8,000, b, c, ...  1790.0  ...   921.0  3736.0
8   [final, neolith, period, roughli, 8,000, b, c,...  1920.0  ...   968.0  3935.0
9   [villag, life, grimspound, late, bronz, age, s...   285.0  ...   125.0   713.0
10  [bronz, age, 3,000, b, c, 1,300, b, c, metalwo...  1096.0  ...   564.0  2620.0
11  [time, period, also, brought, advanc, architec...  1613.0  ...   880.0  1921.0
12  [organ, govern, law, warfar, well, begin, reli...  2210.0  ...  1115.0  2276.0
13  [discoveri, way, heat, forg, iron, kick, iron,...   897.0  ...   424.0  1580.0
14  [along, mass, product, steel, tool, weapon, ag...  1801.0  ...  1220.0  2062.0
15  [agricultur, art, religion, becam, sophist, wr...  1031.0  ...   593.0  1274.0
16  [fact, check, strive, accuraci, fair, see, som...   248.0  ...   272.0   173.0
17  [twice, week, compil, fascin, featur, deliv, s...    38.0  ...    53.0    47.0

[18 rows x 6 columns]

In [23]:
XTest = textosTest.iloc[:,1:].values

In [24]:
XTest

array([[1944., 1855., 1673., 1017., 6510.],
       [1512., 1560., 1401., 1031., 3338.],
       [2155., 2217., 1717., 1168., 7426.],
       [1990., 1629., 1458., 1127., 5799.],
       [1828., 1329., 1338.,  810., 4119.],
       [1004., 1273., 1135.,  977., 1773.],
       [ 652.,  723.,  468.,  350., 1364.],
       [1790., 1478., 1280.,  921., 3736.],
       [1920., 1533., 1390.,  968., 3935.],
       [ 285.,  510.,  399.,  125.,  713.],
       [1096.,  844.,  782.,  564., 2620.],
       [1613., 1490., 1187.,  880., 1921.],
       [2210., 1647., 1423., 1115., 2276.],
       [ 897.,  754.,  692.,  424., 1580.],
       [1801., 1662., 1536., 1220., 2062.],
       [1031.,  968.,  758.,  593., 1274.],
       [ 248.,  281.,  212.,  272.,  173.],
       [  38.,   32.,   41.,   53.,   47.]])

In [25]:
XTestn = XTest / 1000

In [26]:
XTestn


array([[1.944, 1.855, 1.673, 1.017, 6.51 ],
       [1.512, 1.56 , 1.401, 1.031, 3.338],
       [2.155, 2.217, 1.717, 1.168, 7.426],
       [1.99 , 1.629, 1.458, 1.127, 5.799],
       [1.828, 1.329, 1.338, 0.81 , 4.119],
       [1.004, 1.273, 1.135, 0.977, 1.773],
       [0.652, 0.723, 0.468, 0.35 , 1.364],
       [1.79 , 1.478, 1.28 , 0.921, 3.736],
       [1.92 , 1.533, 1.39 , 0.968, 3.935],
       [0.285, 0.51 , 0.399, 0.125, 0.713],
       [1.096, 0.844, 0.782, 0.564, 2.62 ],
       [1.613, 1.49 , 1.187, 0.88 , 1.921],
       [2.21 , 1.647, 1.423, 1.115, 2.276],
       [0.897, 0.754, 0.692, 0.424, 1.58 ],
       [1.801, 1.662, 1.536, 1.22 , 2.062],
       [1.031, 0.968, 0.758, 0.593, 1.274],
       [0.248, 0.281, 0.212, 0.272, 0.173],
       [0.038, 0.032, 0.041, 0.053, 0.047]])

In [163]:
modelo.predict(XTestn[0].reshape(1, -1))

array([[0.01069584, 0.23510857, 0.18105504, 0.14972834, 0.25463772,
        0.16877446]], dtype=float32)

In [164]:
np.argmax(modelo.predict(XTestn[0].reshape(1, -1)))

4

In [165]:
len(vocabularioTest)

10

In [27]:
resultados = {}
for xT in range (len(XTestn)):
  print(np.argmax(modelo.predict(XTestn[xT].reshape(1, -1))),end = " ")
  r = np.argmax(modelo.predict(XTestn[xT].reshape(1, -1)))
  resultados[r] = resultados.get(r, 0) + 1
print()  
resultados

5 5 5 5 5 5 5 5 5 5 5 1 1 5 1 5 4 4 


{1: 3, 4: 2, 5: 13}

In [61]:
print(len(frecuencias))
for i in  frecuencias.keys():
    print(i)
    print(frecuencias[i])

Se han truncado las últimas 5000 líneas del flujo de salida.
('penicillium', 5)
1
('chrysogenum', 5)
1
('bitter', 5)
4
('tast', 5)
2
('deterr', 5)
1
('vocal', 5)
5
('newborn', 5)
2
('incap', 5)
1
('mouth', 5)
3
('larynx', 5)
2
('tongu', 5)
1
('ɔ', 5)
1
('non-human', 5)
1
('322', 5)
1
('323', 5)
1
('324', 5)
1
('vowel', 5)
1
('325', 5)
1
('1983', 5)
1
('hyoid', 5)
3
('apparatu', 5)
2
('technic', 5)
3
('syntax', 5)
2
('harsh', 5)
2
('328', 5)
1
('329', 5)
1
('foxp', 5)
2
('330', 5)
1
("gene'", 5)
1
('331', 5)
1
("broca'", 5)
1
('formul', 5)
1
('sentenc', 5)
1
('neuroscientist', 5)
1
('andrey', 5)
1
('vyshedskiy', 5)
1
('synthesi', 5)
1
('imagin', 5)
1
('infinit', 5)
1
('finit', 5)
1
('spontan', 5)
1
('333', 5)
1
('funer', 5)
2
('336', 5)
1
('337', 5)
2
('338', 5)
1
('339', 5)
1
('non-symbol', 5)
1
('motiv', 5)
1
('1908', 5)
1
('nonnatur', 5)
1
('341', 5)
1
('342', 5)
1
('flower', 5)
3
('bloom', 5)
1
('centauri', 5)
1
('ragwort', 5)
1
('hyacinth', 5)
1
('hollyhock', 5)
1
('343', 5)
1
('ra

In [ ]:
textos = textos.drop("Longitud", axis = 1)
textos

Texto
0   [cuban, missil, crisi, leader, u, soviet, unio...
1   [seiz, power, caribbean, island, nation, cuba,...
2   [know, actor, kevin, costner, 1955, star, movi...
3   [two, superpow, plung, one, biggest, cold, war...
4   [presid, kennedi, brief, situat, octob, 16, im...
5   [american, offici, urgenc, situat, stem, fact,...
6   [soviet, leader, nikita, khrushchev, gambl, se...
7   [outset, crisi, kennedi, excomm, determin, pre...
8   [televis, broadcast, octob, 22, 1962, presid, ...
9   [crucial, moment, unfold, crisi, arriv, octob,...
10  [although, event, sea, offer, posit, sign, war...
11  [despit, enorm, tension, soviet, american, lea...
12  [offici, kennedi, administr, decid, accept, te...
13  [american, soviet, sober, cuban, missil, crisi...
14  [access, hundr, hour, histor, video, commerci,...
15  [fact, check, strive, accuraci, fair, see, som...
16  [cuban, missil, crisi, among, scariest, event,...
17  [1, u, 2, aerial, photograph, analyz, insid, s...
18  [suez, crisi, began, octob, 29, 1956, isra, ar...
19  [august, 5, 1963, repres, unit, state, soviet,...
20  [arm, race, occur, two, countri, increas, size...
21  [nikita, khrushchev, 1894-1971, led, soviet, u...
22  [intern, diplomat, crisi, erupt, may, 1960, un...
23  [earli, 1970, american, oil, consumpt, –, form...
24  [world, war, ii, unit, state, soviet, union, f...

In [ ]:
X = textos.iloc[:,2:].values